services:
  kafka:
    image: apache/kafka:latest
    container_name: nexus-kafka
    ports:
      - "9092:9092"
    environment:
      # Use KRaft mode (No Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Create our topic automatically
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: ["CMD-SHELL", "opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres-db:
    image: postgres:16
    container_name: nexus-db
    environment:
      POSTGRES_DB: nexus_ledger
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nexus_ledger"]
      interval: 5s
      timeout: 5s
      retries: 5

  nexus-app:
    build: .
    container_name: nexus-ledger-app
    depends_on:
      postgres-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      # These are the "Connectors" to other containers
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/nexus_ledger
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

      # These are the "Secrets" (Keep these separate)
      SPRING_DATASOURCE_USERNAME: postgres
      DB_PASSWORD: admin123

      # NEW Identity Secrets
      GITHUB_CLIENT_ID: ${MY_GITHUB_ID}
      GITHUB_CLIENT_SECRET: ${MY_GITHUB_SECRET}

      # Other Config
      SPRING_AI_OLLAMA_BASE_URL: http://host.docker.internal:11434